# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  danger:
    docker:
      - image: cimg/ruby:2.6.8-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - 1-gemsfile-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save cache
          key: 1-gemsfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Execute danger
          command: |
            if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then
              bundle exec danger --fail-on-errors=true
            else
              echo "Not running danger because $DANGER_GITHUB_API_TOKEN is not found"
            fi

workflows:
  danger-workflow:
    jobs:
      - danger
